networks:
  mlops-net:
    driver: bridge

services:
  mlflow-db:
    container_name: dec25-mlops-mlflow-db
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${MLFLOW_DB}
      POSTGRES_USER: ${MLFLOW_USER}
      POSTGRES_PASSWORD: ${MLFLOW_PASSWORD}
    volumes:
      - mlflow_db_data:/var/lib/postgresql/data
    networks:
      - mlops-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_USER} -d ${MLFLOW_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow-server:
    container_name: dec25-mlops-mlflow-server
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    ports:
      - "${MLFLOW_PORT}:5000"
    env_file:
      - .env
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://${MLFLOW_USER}:${MLFLOW_PASSWORD}@mlflow-db/${MLFLOW_DB}
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /app/mlflow/artifacts
    depends_on:
      mlflow-db:
        condition: service_healthy
    volumes:
      - ./mlflow/artifacts:/app/mlflow/artifacts
    networks:
      - mlops-net
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://${MLFLOW_USER}:${MLFLOW_PASSWORD}@mlflow-db/${MLFLOW_DB}
      --default-artifact-root /app/mlflow/artifacts

  ml_training:
    container_name: velib_ml
    build:
      context: .
      dockerfile: ml/Dockerfile
      target: training
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MODEL_STAGE: ${ML_MODEL_STAGE}
    volumes:
      - ./ml:/app/ml
      - ./data:/app/data
      - ./shared:/app/shared
      - ./mlflow/artifacts:/app/mlflow/artifacts
    networks:
      - mlops-net
    depends_on:
      - mlflow-server
    command: python ml/src/main.py

  jupyter-service:
    container_name: dec25-mlops-jupyter
    build:
      context: .
      dockerfile: ml/Dockerfile
      target: jupyter
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./ml:/app/ml
      - ./shared:/app/shared
      - ./ml/notebooks:/app/notebooks
      - ./data:/app/data
    user: "1000:1000"
    networks:
      - mlops-net
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/app
      --IdentityProvider.token=${JUPYTER_TOKEN}
      --ServerApp.disable_check_xsrf=True
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - mlflow-server
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
      MODEL_STAGE: ${API_MODEL_STAGE}
    volumes:
      - ./api:/app/api
      - ./shared:/app/shared
      - ./mlflow/artifacts:/mlflow/artifacts
    networks:
      - mlops-net
    command: uvicorn api.velib_api.main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    build:
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployments/nginx/certs:/etc/nginx/certs:ro
      - ./deployments/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - api
    networks:
      - mlops-net

volumes:
  mlflow_db_data: