[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
description = "Package partagé pour le projet Vélib"
requires-python = ">=3.12"
dependencies = [
    "sqlalchemy>=2.0.0",
    "pandas>=2.0,<3",
    "psycopg2-binary",
    "python-dotenv"
]